### ISSUE TITLE
Slides

### ISSUE THREAD

**Issue by johanrhodin** [dzimmer/ZimmersModelicaTutorial#7]
If any slides where used during the presentation it would be nice to have them in the repo.

**Comment by tbeu** [comment]
This would be very helpful indeed. I knew the 10 step-by-step models before the presentation at the 11. Modelica Conference, but I only saw the actual modeling mind from the slides at the presentation. Knowing the mind that goes from each step to the next really is important here.

**Comment by johanrhodin** [comment]
@dzimmer Do you have these slides around?

**Comment by tbeu** [comment]
I pointed @dzimmer by mail to this issue. Let's see.

**Comment by dzimmer** [comment]
Thanks for reminding me. Unfortunately sometimes needed. Long overdue

I have no uploaded the slides and a corresponding intro paper. Let me know whether this material is helpful
